alias g='git'
alias gs='git status -sb'
alias gcheck='git checkout'
alias gc='git commit'
alias gl='git log --oneline --graph -15'
alias wb='~/quicklisp/local-projects/weather/weather bergen'
alias weather='~/quicklisp/local-projects/weather/weather'
